#ifndef WEB_PAGES_H
#define WEB_PAGES_H

/* 配网页面：深色主题，手机友好
 * 访问地址：设备发 AP 时 → http://192.168.4.1
 *           设备连上路由后 → http://<设备IP>（备用）
 *
 * API:
 *   GET  /           → 本页面
 *   GET  /status     → JSON { ap_ssid, sta_ssid, sta_ip, aida64_ip, rssi }
 *   POST /api/config → JSON { sta_ssid, sta_pass, aida64_ip }
 *                      成功 200 { success: true }
 *                      失败 400 { error: "..." }
 */

/* 手机友好的深色配网页面（嵌入式 C 字符串） */
static const char INDEX_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"zh\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">"
"<title>AIDA64 Monitor</title>"
"<style>"
"* { box-sizing: border-box; margin: 0; padding: 0; }"
"body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; "
       "background: #0A0E1A; color: #F9FAFB; min-height: 100vh; padding: 16px; }"

".header { text-align: center; padding: 20px 0 16px; }"
".header h1 { font-size: 24px; font-weight: 700; color: #2563EB; margin-bottom: 4px; }"
".header p { font-size: 13px; color: #9CA3AF; }"

".card { background: #111827; border-radius: 12px; padding: 16px; margin-bottom: 14px; "
        "border: 1px solid #1F2937; }"
".card-title { font-size: 11px; font-weight: 600; color: #6B7280; text-transform: uppercase; "
              "letter-spacing: 0.08em; margin-bottom: 12px; }"

".status-row { display: flex; justify-content: space-between; align-items: center; padding: 6px 0; }"
".status-row:not(:last-child) { border-bottom: 1px solid #1F2937; }"
".status-label { font-size: 13px; color: #9CA3AF; }"
".status-value { font-size: 13px; color: #F9FAFB; font-weight: 500; word-break: break-all; text-align: right; }"
".status-badge { display: inline-block; padding: 2px 8px; border-radius: 20px; font-size: 11px; font-weight: 600; }"
".badge-green { background: rgba(22,163,74,0.2); color: #16A34A; }"
".badge-red   { background: rgba(239,68,68,0.2);  color: #EF4444; }"
".badge-blue  { background: rgba(37,99,235,0.2); color: #2563EB; }"

".form-group { margin-bottom: 14px; }"
".form-label { display: block; font-size: 12px; color: #9CA3AF; margin-bottom: 6px; }"
".form-input { width: 100%; background: #1F2937; border: 1px solid #374151; border-radius: 8px; "
              "padding: 10px 12px; color: #F9FAFB; font-size: 14px; outline: none; "
              "transition: border-color 0.2s; }"
".form-input:focus { border-color: #2563EB; }"
".form-hint { font-size: 11px; color: #6B7280; margin-top: 4px; }"

".btn { width: 100%; background: #2563EB; color: #fff; border: none; border-radius: 10px; "
       "padding: 14px; font-size: 15px; font-weight: 600; cursor: pointer; margin-top: 8px; "
       "transition: background 0.2s; }"
".btn:hover { background: #1D4ED8; }"
".btn:active { background: #1E40AF; }"
".btn:disabled { background: #374151; color: #6B7280; cursor: not-allowed; }"
".btn-loading { position: relative; }"
".btn-loading::after { content: ''; display: inline-block; width: 14px; height: 14px; "
                       "border: 2px solid #fff; border-top-color: transparent; border-radius: 50%; "
                       "animation: spin 0.7s linear infinite; margin-left: 8px; vertical-align: middle; }"
"@keyframes spin { to { transform: rotate(360deg); } }"

".msg { padding: 10px 14px; border-radius: 8px; font-size: 13px; margin-top: 12px; display: none; }"
".msg-ok    { background: rgba(22,163,74,0.15); color: #16A34A; border: 1px solid rgba(22,163,74,0.3); }"
".msg-err   { background: rgba(239,68,68,0.15);  color: #EF4444; border: 1px solid rgba(239,68,68,0.3); }"

".footer { text-align: center; font-size: 11px; color: #4B5563; margin-top: 24px; padding-bottom: 16px; }"

".rssi-bar { display: flex; align-items: center; gap: 4px; }"
".rssi-seg { width: 4px; border-radius: 2px; background: #374151; }"
".rssi-seg.active { background: #16A34A; }"
"</style>"
"</head>"
"<body>"

"<div class=\"header\">"
"  <h1>AIDA64 Monitor</h1>"
"  <p id=\"status-badge\">初始化中...</p>"
"</div>"

"<div class=\"card\">"
"  <div class=\"card-title\">设备状态</div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">运行模式</span>"
"    <span class=\"status-value\"><span id=\"dev-mode\" class=\"status-badge badge-blue\">--</span></span>"
"  </div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">热点名称 (AP)</span>"
"    <span class=\"status-value\" id=\"ap-ssid\">--</span>"
"  </div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">热点 IP</span>"
"    <span class=\"status-value\">192.168.4.1</span>"
"  </div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">连接 WiFi</span>"
"    <span class=\"status-value\" id=\"sta-ssid\">--</span>"
"  </div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">设备 IP</span>"
"    <span class=\"status-value\" id=\"sta-ip\">--</span>"
"  </div>"
"  <div class=\"status-row\">"
"    <span class=\"status-label\">信号强度</span>"
"    <span class=\"status-value\">"
"      <span class=\"rssi-bar\" id=\"rssi-bar\">"
"        <span class=\"rssi-seg\" style=\"height:6px\"></span>"
"        <span class=\"rssi-seg\" style=\"height:10px\"></span>"
"        <span class=\"rssi-seg\" style=\"height:14px\"></span>"
"        <span class=\"rssi-seg\" style=\"height:18px\"></span>"
"      </span>"
"      <span id=\"rssi-db\" style=\"margin-left:6px\">-- dBm</span>"
"    </span>"
"  </div>"
"</div>"

"<div class=\"card\">"
"  <div class=\"card-title\">WiFi 配置</div>"
"  <div class=\"form-group\">"
"    <label class=\"form-label\">要连接的 WiFi 名称</label>"
"    <input class=\"form-input\" type=\"text\" id=\"sta-ssid-input\" placeholder=\"例如：CMCC-CGzH\" autocomplete=\"off\" autocorrect=\"off\" autocapitalize=\"none\">"
"  </div>"
"  <div class=\"form-group\">"
"    <label class=\"form-label\">WiFi 密码</label>"
"    <input class=\"form-input\" type=\"password\" id=\"sta-pass-input\" placeholder=\"留空则使用无密码网络\" autocomplete=\"new-password\">"
"  </div>"
"</div>"

"<div class=\"card\">"
"  <div class=\"card-title\">AIDA64 服务器</div>"
"  <div class=\"form-group\">"
"    <label class=\"form-label\">AIDA64 电脑 IP 地址</label>"
"    <input class=\"form-input\" type=\"text\" id=\"aida64-ip-input\" placeholder=\"例如：192.168.1.121\" "
           "autocomplete=\"off\" autocorrect=\"off\" spellcheck=\"false\">"
"    <p class=\"form-hint\">AIDA64 RemoteSensor 端口默认 7789</p>"
"  </div>"
"</div>"

"<button class=\"btn\" id=\"save-btn\" onclick=\"saveConfig()\">保存配置</button>"

"<div id=\"msg-ok\"  class=\"msg msg-ok\"></div>"
"<div id=\"msg-err\" class=\"msg msg-err\"></div>"

"<div class=\"footer\">ESP32-S3 AIDA64 Monitor &nbsp;|&nbsp; <span id=\"fw-ver\">v1.0</span></div>"

"<script>"
"let devMode = 'AP'; // 页面加载时默认 AP 模式"

"// 轮询设备状态"
"async function pollStatus(){"
"  try {"
"    let r = await fetch('/status');"
"    let j = await r.json();"
"    applyStatus(j);"
"  } catch(e) { console.log('status poll err', e); }"
"}"

"function applyStatus(s){"
"  document.getElementById('dev-mode').textContent = s.mode || '--';"
"  document.getElementById('dev-mode').className  = 'status-badge ' + (s.mode==='STA' ? 'badge-green' : 'badge-blue');"
"  document.getElementById('ap-ssid').textContent   = (s.ap_ssid  || '--');"
"  document.getElementById('sta-ssid').textContent = (s.sta_ssid || '--');"
"  document.getElementById('sta-ip').textContent   = (s.sta_ip   || '--');"
"  document.getElementById('status-badge').textContent = s.mode==='STA' ? '已连接网络' : '待配置网络';"

"  // RSSI 信号条"
"  let rssi = s.rssi || -100;"
"  let bars = document.querySelectorAll('.rssi-seg');"
"  let active = 0;"
"  if(rssi > -50) active = 4;"
"  else if(rssi > -60) active = 3;"
"  else if(rssi > -70) active = 2;"
"  else if(rssi > -80) active = 1;"
"  bars.forEach((b,i)=> b.classList.toggle('active', i < active));"
"  document.getElementById('rssi-db').textContent = rssi + ' dBm';"

"  // 如果已连接，自动填充表单"
"  if(s.sta_ssid) document.getElementById('sta-ssid-input').value = s.sta_ssid;"
"  if(s.aida64_ip) document.getElementById('aida64-ip-input').value = s.aida64_ip;"
"}"

"async function saveConfig(){"
"  let ssid  = document.getElementById('sta-ssid-input').value.trim();"
"  let pass  = document.getElementById('sta-pass-input').value;"
"  let aida  = document.getElementById('aida64-ip-input').value.trim();"
"  let btn   = document.getElementById('save-btn');"

"  if(!ssid){ showMsg('err','WiFi 名称不能为空'); return; }"

"  btn.disabled = true;"
"  btn.classList.add('btn-loading');"
"  btn.textContent = '正在保存';"
"  hideMsgs();"

"  try {"
"    let r = await fetch('/api/config',{"
"      method:'POST',"
"      headers:{'Content-Type':'application/json'},"
"      body: JSON.stringify({ sta_ssid: ssid, sta_pass: pass, aida64_ip: aida })"
"    });"
"    let j = await r.json();"
"    if(j.success){"
"      showMsg('ok','配置已保存，设备正在重启...');"
"      btn.textContent = '已保存，重启中';"  
"      setTimeout(()=> location.reload(), 4000);"
"    } else {"
"      showMsg('err', j.error || '保存失败');"
"      btn.disabled = false;"
"      btn.classList.remove('btn-loading');"
"      btn.textContent = '保存配置';"
"    }"
"  } catch(e){"
"    showMsg('err','网络错误：' + e.message);"
"    btn.disabled = false;"
"    btn.classList.remove('btn-loading');"
"    btn.textContent = '保存配置';"
"  }"
"}"

"function showMsg(type, text){"
"  document.getElementById('msg-'+type).style.display='block';"
"  document.getElementById('msg-'+type).textContent = text;"
"  window.scrollTo({top: document.body.scrollHeight, behavior:'smooth'});"
"}"
"function hideMsgs(){"
"  document.getElementById('msg-ok').style.display='none';"
"  document.getElementById('msg-err').style.display='none';"
"}"

"// 启动轮询"
"pollStatus();"
"setInterval(pollStatus, 3000);"
"</script>"
"</body>"
"</html>";

#endif /* WEB_PAGES_H */
